apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hitl-refund-secrets
  namespace: hitl-refund
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: "5b984100-4839-43d3-b923-be878e4019b7"
    keyvaultName: "key-human"
    tenantId: "3ad7ab73-4c91-4d09-a567-1e747a70c126"

    objects: |
      array:
        - |
          objectName: cosmos-key
          objectType: secret
        - |
          objectName: openrouter-api-key
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret

  secretObjects:
    - secretName: hitl-refund-secrets
      type: Opaque
      data:
        - objectName: cosmos-key
          key: COSMOS_KEY
        - objectName: openrouter-api-key
          key: OPENROUTER_API_KEY
        - objectName: postgres-password
          key: POSTGRES_PASSWORD
