apiVersion: v1
kind: Service
metadata:
  name: hitl-refund
  namespace: hitl-refund
spec:
  type: ClusterIP
  selector:
    app: hitl-refund
  ports:
    - name: http
      port: 80
      targetPort: 8501
      protocol: TCP
